<a href="https://colab.research.google.com/github/julika333/TMS-DS/blob/main/00_%D0%B7%D0%BD%D0%B5%D1%80%D1%89%D0%BA%D1%81%D1%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("assd")

assd


In [1]:
!nvidia-smi

Tue May 21 18:39:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.0+cu121


In [ ]:
scalar = torch.tensor(7)

scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[[7,8],[2,3],[4,5]]])

In [ ]:
matrix.shape


torch.Size([1, 3, 2])

In [ ]:
matrix.ndim

3

In [ ]:
rand_tensor = torch.rand(3, 4)

In [ ]:
rand_tensor

tensor([[1.3620e-04, 7.6296e-01, 2.2920e-01, 1.3505e-01],
        [2.0088e-01, 8.3794e-01, 3.4194e-01, 8.1382e-01],
        [7.6834e-01, 1.7484e-01, 9.2469e-01, 5.5122e-01]])

In [ ]:
rand_img_size_tensor = torch.rand(size=(3,4,2))

In [ ]:
rand_img_size_tensor

tensor([[[0.0392, 0.4415],
         [0.1495, 0.6830],
         [0.6795, 0.4707],
         [0.2702, 0.4265]],

        [[0.7043, 0.8637],
         [0.1398, 0.7194],
         [0.8160, 0.7531],
         [0.9187, 0.4433]],

        [[0.4886, 0.4324],
         [0.2361, 0.6427],
         [0.3857, 0.3493],
         [0.0701, 0.5174]]])

In [ ]:
zero = torch.zeros(size=(1,10))
zero

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=rand_img_size_tensor)
ten_zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
new_tensor = int_32_tensor * float_32_tensor

In [ ]:
print(f"Datatype: {new_tensor.dtype}")
print(f"Shape: {new_tensor.shape}")
print(f"Device: {new_tensor.device}")

Datatype: torch.float32
Shape: torch.Size([3])
Device: cpu


In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor / 10


tensor([0.1000, 0.2000, 0.3000])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
print(tensor)
print(tensor * tensor)

tensor([1, 2, 3])
tensor([1, 4, 9])


In [ ]:
%%time
value = torch.matmul(tensor, tensor)
value

CPU times: user 87 µs, sys: 0 ns, total: 87 µs
Wall time: 90.8 µs


tensor(14)

In [ ]:
%%time
value =0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.24 ms, sys: 14 µs, total: 1.26 ms
Wall time: 1.15 ms


tensor(14)

In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.1579, 0.3613, 0.4743, 0.1735],
        [0.2683, 1.0758, 1.2110, 0.3295]])

In [ ]:
tensor_A = torch.rand(3,2)
tensor_B = torch.rand(3,2)

In [ ]:
torch.mm(tensor_A, tensor_B.T)

tensor([[0.5640, 0.3619, 0.2817],
        [0.1273, 0.1909, 0.0828],
        [1.1296, 0.9568, 0.6050]])

In [ ]:
x = torch.arange(0,100,10)
print(x)
print(torch.min(x))
print(x.max())
print(torch.mean(x.type(torch.float32)))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0)
tensor(90)
tensor(45.)


In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_resh = x.reshape(1, 9)
x_resh, x_resh.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_resh.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [ ]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[0, 1, 2]

tensor(6)

In [ ]:
x[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
import torch
import numpy as np

array  = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

rtA = torch.rand(3, 4)
rtB = torch.rand(3, 4)
print(rtA)
print(rtB)
print(rtA == rtB)

tensor([[0.7967, 0.5526, 0.2842, 0.0498],
        [0.3292, 0.6497, 0.2985, 0.5300],
        [0.6375, 0.5731, 0.9026, 0.5738]])
tensor([[0.8985, 0.7267, 0.4788, 0.6830],
        [0.4568, 0.4023, 0.3363, 0.2260],
        [0.1022, 0.7544, 0.6484, 0.0787]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42)
rtC = torch.rand(3, 4)
torch.manual_seed(42)
rtD = torch.rand(3, 4)
print(rtC)
print(rtD)
print(rtC == rtD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Tue Jan  2 21:43:37 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_cpu = tensor_on_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')